### ISSUE TITLE
Consider changing to `send_now` and `send_later`?

### ISSUE THREAD

**Issue by paulcsmith** [paulcsmith/bamboo#102]
I originally went with `deliver` because Elixir uses `send` when talking about sending messages. But the more I think about it, the more I think most people will alias their Mailer and call it like `Mailer.deliver_now/send_now`. I don't think they'll import the Mailer. So I think that it might make sense to rename everything with `deliver*` to `send*`. It's easier to type and I think it's the common way people talk about email. No one "delivers" an email, they send them. 

I'd like to get this nailed down before releasing 1.0 and writing a blog post on it since it would totally change the API and most of the docs

Thoughts on this? cc @blakewilliams @drapergeek

**Comment by drapergeek** [comment]
I think I'd vote for sticking with `deliver`, `send` seems to be used for more "programming" type interfaces and I'd rather stick to that.

**Comment by paulcsmith** [comment]
@drapergeek Good call. I think I'll leave it as-is
