### ISSUE TITLE
assert_delivered_email with options

### ISSUE THREAD

**Issue by paulcsmith** [paulcsmith/bamboo#47]
Usually `assert_delivered_email(Email.welcome_email(user)` will work fine, but there are cases when it won't

I think I should add `assert_delivered_email(subject: "Something")` in case you can't/don't want to assert against a whole email.

**This would be helpful if parts of the email have state that would make it difficult to test the whole email.** For example, if a token is generated in the text/html_body from Phoenix.Token, then the body would be different every time since the token would change. So it might be better to assert just a few of the most important fields.

**Comment by paulcsmith** [comment]
This might be another helpful solution, given the scenario in the original issue, where asserting against the whole email would not work because parts of the email body have a randomly generated token.

```elixir
assert_delivered_email(Emails.welcome_email(user), skip: [:html_body, :text_body])
```

This assertion would check that an email was delivered with the subject, to, from, headers, etc., but would not check the fields in `skip` option.
 
Any thoughts on this @blakewilliams @drapergeek @stevedomin?

**Comment by BlakeWilliams** [comment]
What about grabbing the sent email and using `assert` like you do in the README?

```
    assert email.to == "someone@foo.com"
    assert email.subject == "This is your welcome email"
    assert email.html_body =~ "Welcome to the app!"
```

Could we make `email` be the delivered email?

**Comment by paulcsmith** [comment]
My thought is that you should unit test the email like in the readme, but then in integration tests you should avoid repeating the subject, and things like that because it leads to shotgun surgery. If you change the subject you would have to change it in the unit test and anywhere else you used it in integration tests. The benefit of `assert_delivered_email` is that you don’t have that repetition.

I’d like to keep it so that there is as little duplication between unit tests and integration tests as possible. With that said I think you’re right that it might be good to add a function like `get_delivered_email` that returns the sent email. The downside is that you couldn’t really use that if you sent more than one email since it would just grab the first one :S So I’m not sure how to make that more useful/less error prone

**Comment by paulcsmith** [comment]
Decided to stick with just the keyword options for now. Still considering adding something like `get_deliver_email` and/or a way to easily skip checking the body. Still not sure that's a good idea so I'm holding off on it.

**Comment by paulcsmith** [comment]
See #74
