### ISSUE TITLE
Don't use Task.async in deliver_async

### ISSUE THREAD

**Issue by stevedomin** [paulcsmith/bamboo#59]
`Task.async` is linking the task process with the parent process so if the latter dies first it will kill the former.

For example, with Phoenix it would mean that a HTTP request could finish before we actually had a chance to send the email.

Elixir 1.2 introduced [Task.async_no_link](http://elixir-lang.org/docs/stable/elixir/Task.Supervisor.html#async_nolink/2) which could be used here.

Happy to submit a PR if you think that's the way to go.

**Comment by paulcsmith** [comment]
I admit that Supervisors and Task are a weakspot for me, so I'm not totally sure of the way to go. I definitely see that Task.async is a problem though. I think what we may want to do is use Task.Supervisor. Maybe something like:

```elixir
Task.Supervisor.start_child Task.Supervisor.start_link, fn -> 
  deliver(email, config) 
end
```

I *think* this might be what we want because really I don't want the delivery to be "async" I want it to be in the background and you just send it off, you don't await. So I believe this should work because the docs this about Task.Supervisor.start_child 

> Note that the spawned process is not linked to the caller, but only to the supervisor. This command is useful in case the task needs to perform side-effects (like I/O) and does not need to report back to the caller

Thoughts?

**Comment by sorentwo** [comment]
This issue, and the discussion about it on IRC yesterday, was perfectly timed. I'm just now starting to integrate email into an application and would like to make use of Bamboo.

I was surprised to see that delivery wasn't being handled by a server and used Task.async instead. I've looked through the source and the structure a bit and think it would really benefit from `Bamboo.Mailer` being a GenServer that is configured with the adapter and simply exposes `deliver`/`deliver_async` API functions. That would move the work of actually delivering the emails outside of the caller and let the worker be managed by the application.

I've begun work on this in my fork and would love to contribute it back with your approval @paulcsmith.

**Comment by paulcsmith** [comment]
@sorentwo Thank you very much! I hope Bamboo works well for you. I would definitely appreciate contributions, but I am unsure of the best direction to. My thought is that I'd like to do something like this:

```elixir
# Instruct users to put this in their supervision tree
supervisor(Task.Supervisor, [[name: Bamboo.Mailer]]) # Name could be whatever makes sense

# In the MandrillAdapter
def deliver_later(email, config) do
end
```

**Comment by paulcsmith** [comment]
Chatted with @sorentwo for a bit on iRC and I think something like this would work: https://gist.github.com/paulcsmith/7e716a215775873a30ac

Bamboo would define a default deliver_later strategy using Task.Supervisor. Adapters can choose to implement a deliver_later function or not. You can create a custom adapter if you want to do something different when delivering later (see example at the end)
