### ISSUE TITLE
Extract helpers for fake servers

### ISSUE THREAD

**Issue by paulcsmith** [paulcsmith/bamboo#7]
https://github.com/paulcsmith/bamboo/blob/master/test/lib/bamboo/mandrill_adapter_test.exs#L17

Could probably make a new hex package out of this actually

**Comment by scrogson** [comment]
How about just using [Bypass](https://github.com/pspdfkit-labs/bypass) for that?

**Comment by paulcsmith** [comment]
I checked that out, but I didn't like how the assertions were made. I prefer to make the assertions at the end of the test instead of mixing the assertions with the response. I also have some ideas for making things a removing some of the boilerplate that Bypass requires. Maybe it will be worse, maybe it will be better :) We'll see

**Comment by scrogson** [comment]
Have a look at what I've done here: https://github.com/scrogson/oauth2/blob/master/test/support/test_helpers.ex#L6-L54

**Comment by paulcsmith** [comment]
Very cool. I like what you've done. I will probably use some of those ideas. One thing I want to try to do is introduce as little extra API as possible and mostly stick to using regular plugs and the Plug.Router. We'll see. I haven't really thought it through all the way, but I'll try out on this project and see how it works :)
