### ISSUE TITLE
Remove deliver_later_strategy and  add delivery_strategy options. Add deliver_now for delivering right away

### ISSUE THREAD

**Issue by paulcsmith** [paulcsmith/bamboo#89]
I think this makes the library a bit easier to use. That way `deliver` uses the strategy you want and if you want to deliver right away then you use `deliver_sync`. This essentially flips how the current mailer works.

Still not 100% sold on the name though. Function name ideas:

* deliver_now
* deliver_sync
* deliver_blocking (though it's not really blocking so maybe a bad name)

**Comment by gshaw** [comment]
Unless there is a good reason to use a different name I'd suggest leveraging what Rails is using and go with `deliver_now`.

**Comment by paulcsmith** [comment]
@gshaw I wasn't aware that Rails changed to deliver_now. I kind of like that so I think that might be fine. So `deliver` will use whatever strategy you decide and `deliver_now` will deliver immediately and wait for a response until it returns.

How does that sound?

**Comment by gshaw** [comment]
Rails went with `deliver_now` and `deliver_later` to match ActiveJob's `perform_now` and `perform_later` methods.  I find those names are very explicit and easy to work with.
http://edgeapi.rubyonrails.org/classes/ActionMailer/MessageDelivery.html

**Comment by paulcsmith** [comment]
The (potential) problem with `deliver_later` is that it doesn't necessarily deliver later. The deliver_later call could be done with a TaskSupervisor which will start delivery immediately, but does so in the background. Maybe that difference doesn't really matter in practice though and having `deliver_later` and `deliver_now` is a good distinction.

**Comment by paulcsmith** [comment]
Thanks for the feedback @gshaw. I went with deliver_later and deliver_now
